### ISSUE TITLE
代码分拆

### ISSUE THREAD

**Issue by erlv** [Jerry-Ling/shuzu#4]
1.  使用Makefile管理源代码文件的
2.  将目前单个文件包含所有程序运行所需源代码的代码组织方式修改为 Makefile+多个源代码文件的形式。 其中：
  1. 所有打印相关的代码保存在print.cpp文件中，所有数组初始化相关的代码保存在 init.cpp文件中。
  2. main.cpp函数中应该只包含main函数。
  3. 为print.cpp和init.cpp分别创建头文件 print.hpp和init.hpp， 这两个头文件中包含main.cpp中代码所需的函数和全局变量的声明
  
此任务需要对Makefile和头文件定义有一些了解，做之前咱们先讨论一次。

**Comment by Jerry-Ling** [comment]
我把他们拆分之后直接运行main.cpp可以直接运行
makefile这个忘了怎么弄了，我晚上回来再看看。

**Comment by Jerry-Ling** [comment]
我把他们拆分之后直接运行main.cpp可以直接运行
makefile这个忘了怎么弄了，我晚上回来再看看。

**Comment by erlv** [comment]
增加Makefile会让命令行运行更方便。 还能找到之前我给你做演示的那个Makefile吗？
